export const printHelp = () => {
  console.log("fexapi-cli");
  console.log("");
  console.log("Usage:");
  console.log("  fexapi init [--force]");
  console.log("  fexapi generate");
  console.log("  fexapi serve [--host <host>] [--port <number>]");
  console.log("  fexapi run [--host <host>] [--port <number>]");
  console.log("  fexapi [--host <host>] [--port <number>]");
  console.log("  fexapi --help");
  console.log("");
  console.log("Examples:");
  console.log("  fexapi init");
  console.log("  fexapi init --force");
  console.log("  fexapi generate");
  console.log("  fexapi serve --host 127.0.0.1 --port 5000");
  console.log("  fexapi --port 4000");
  console.log("");
  console.log("Package manager usage:");
  console.log("  npx fexapi init");
  console.log("  pnpm dlx fexapi init");
  console.log("  yarn dlx fexapi init");
  console.log("");
  console.log("`fexapi init` creates:");
  console.log("  fexapi.config.json");
  console.log("  fexapi/schema.fexapi");
  console.log("");
  console.log("Then run:");
  console.log("  # edit fexapi/schema.fexapi");
  console.log("  fexapi generate");
  console.log("  fexapi run");
  console.log("");
  console.log("Generate output:");
  console.log("  fexapi/generated.api.json");
  console.log("  fexapi/migrations/*.json");
};
